// Code generated by protoc-gen-go. DO NOT EDIT.
// source: iss.proto

package iss_api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type IssRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IssRequest) Reset()         { *m = IssRequest{} }
func (m *IssRequest) String() string { return proto.CompactTextString(m) }
func (*IssRequest) ProtoMessage()    {}
func (*IssRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4352da8c8d17a2a0, []int{0}
}

func (m *IssRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IssRequest.Unmarshal(m, b)
}
func (m *IssRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IssRequest.Marshal(b, m, deterministic)
}
func (m *IssRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IssRequest.Merge(m, src)
}
func (m *IssRequest) XXX_Size() int {
	return xxx_messageInfo_IssRequest.Size(m)
}
func (m *IssRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IssRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IssRequest proto.InternalMessageInfo

type IssReply struct {
	Longitude            string   `protobuf:"bytes,1,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Latitude             string   `protobuf:"bytes,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IssReply) Reset()         { *m = IssReply{} }
func (m *IssReply) String() string { return proto.CompactTextString(m) }
func (*IssReply) ProtoMessage()    {}
func (*IssReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_4352da8c8d17a2a0, []int{1}
}

func (m *IssReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IssReply.Unmarshal(m, b)
}
func (m *IssReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IssReply.Marshal(b, m, deterministic)
}
func (m *IssReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IssReply.Merge(m, src)
}
func (m *IssReply) XXX_Size() int {
	return xxx_messageInfo_IssReply.Size(m)
}
func (m *IssReply) XXX_DiscardUnknown() {
	xxx_messageInfo_IssReply.DiscardUnknown(m)
}

var xxx_messageInfo_IssReply proto.InternalMessageInfo

func (m *IssReply) GetLongitude() string {
	if m != nil {
		return m.Longitude
	}
	return ""
}

func (m *IssReply) GetLatitude() string {
	if m != nil {
		return m.Latitude
	}
	return ""
}

func init() {
	proto.RegisterType((*IssRequest)(nil), "iss_api.IssRequest")
	proto.RegisterType((*IssReply)(nil), "iss_api.IssReply")
}

func init() { proto.RegisterFile("iss.proto", fileDescriptor_4352da8c8d17a2a0) }

var fileDescriptor_4352da8c8d17a2a0 = []byte{
	// 157 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcc, 0x2c, 0x2e, 0xd6,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xcf, 0x2c, 0x2e, 0x8e, 0x4f, 0x2c, 0xc8, 0x54, 0xe2,
	0xe1, 0xe2, 0xf2, 0x2c, 0x2e, 0x0e, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x51, 0x72, 0xe1, 0xe2,
	0x00, 0xf3, 0x0a, 0x72, 0x2a, 0x85, 0x64, 0xb8, 0x38, 0x73, 0xf2, 0xf3, 0xd2, 0x33, 0x4b, 0x4a,
	0x53, 0x52, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x10, 0x02, 0x42, 0x52, 0x5c, 0x1c, 0x39,
	0x89, 0x25, 0x10, 0x49, 0x26, 0xb0, 0x24, 0x9c, 0x6f, 0xe4, 0xc7, 0x25, 0xe0, 0x93, 0x9f, 0x9c,
	0x58, 0x92, 0x99, 0x9f, 0xe7, 0x92, 0x5a, 0x92, 0x9a, 0x5c, 0x92, 0x5f, 0x24, 0x64, 0xc5, 0xc5,
	0xe7, 0x9e, 0x5a, 0xe2, 0x59, 0x5c, 0x0c, 0x93, 0x11, 0x12, 0xd6, 0x83, 0xba, 0x41, 0x0f, 0xe1,
	0x00, 0x29, 0x41, 0x54, 0xc1, 0x82, 0x9c, 0x4a, 0x25, 0x86, 0x24, 0x36, 0xb0, 0x9b, 0x8d, 0x01,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x14, 0xb1, 0xbd, 0xd5, 0xc0, 0x00, 0x00, 0x00,
}
